language: ruby
rvm:
  - 2.7.0

env:
  global:
    - secure: "lqhy6T3eQlupJCTBI1b5aGAScrSo2jJL4TcOiB05vwWl5pEKTczvXA/GBjpaWxcJzYW6iXrXGO+7rJ/QjMiuKWbHxKEGCoMkTY7wxJWD96lPeQALNjjkP36Yz6UACKZNhDwAOZv5j7WehbZSYNU4uLIUTTvOzZ81hjxS7ZdiocXmk48csrSA6dsnM5aKAwq/zwfu5j7krL9E9tDIQY1p4apggLzokYpOxdknb/fDbMtxmHuO6mFZAgm2nwYNW/TMg/LLgLBjh8IQcR25TtL6/L8qWpoGAyqGuiz3AZ48Z6CIc5ftoFBWLqm97n5iwEbauxsm2n2C/UbDeuJh5G/086Sya5nKGcI1ekMBAPHne1IAYMs286gdvHC1STa5fT1MLtsqLeJfvP0rqDFtKUbZCQBFqfgHHr+EST4yyWGMhRhK6K0eDORZ5pMGFnBwXXyvBsAxUFgioVHQeW3+FioyPjoIc9W4h71MAz8kHCeuCcN0kBS8vVBg366K3CBcWW1tBqC65YAvojtHtEOa/j0ozxBA3VJFDOXm4XL750zDMRnUTuuuFOH1KYwhirEYqlZhRfvFgHs+qXmnlrbhQLxy008W1kivY58VqgSeFmrRcZ27Ka5/FXgeQGx5B64XPM89LbjpTLahjOh/6vvNnG2CToJmuNbb9N9VJMdZnAiTaEc="

before_install:
  # Here, we decrypt a passwordless ssh key for acting as a user on the server named "travis"
  #   # See: https://docs.travis-ci.com/user/encrypting-files/#Automated-Encryption
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ] && [ "$TRAVIS_BRANCH" = "master" ]; then openssl aes-256-cbc -K $encrypted_ecd13b88eda4_key -iv $encrypted_ecd13b88eda4_iv -in _scripts/id_rsa-production.enc -out _scripts/id_rsa-production -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ] && [ "$TRAVIS_BRANCH" = "master" ]; then chmod 400 _scripts/id_rsa-production; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ] && [ "$TRAVIS_BRANCH" = "staging" ]; then openssl aes-256-cbc -K $encrypted_d3974dc451dd_key -iv $encrypted_d3974dc451dd_iv -in _scripts/id_rsa-staging.enc -out _scripts/id_rsa-staging -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ] && [ "$TRAVIS_BRANCH" = "staging" ]; then chmod 400 _scripts/id_rsa-staging; fi
  # Bundler 2.0 support
  # See: https://docs.travis-ci.com/user/languages/ruby/#bundler-20
  - gem update --system
  - gem install bundler

before_script:
  # Build Jekyll site
  - bundle exec jekyll build

cache: bundler

#script: travis_retry bundle exec htmlproofer --check-html --allow-hash-href ./_site

deploy:
  - provider: script
    script: if [ "$TRAVIS_BRANCH" = "staging" ]; then echo "Deploying to staging"; bash -x _scripts/deploy.sh deploy _scripts/id_rsa-staging bw1.staging.hypha.coop 8003 /var/www/staging.hypha.coop; elif [ "$TRAVIS_BRANCH" = "master" ]; then echo "Deploying to production"; bash -x _scripts/deploy.sh deploy _scripts/id_rsa-production bw1.hypha.coop 1003 /var/www/hypha.coop; fi
    cleanup: false
    on:
      branch:
        - master
        - staging
  - provider: script
    script: tar -czvf www.tar.gz -C _site . && bash -x _scripts/deploy-dweb.sh "$DISTRIBUTED_PRESS_API_KEY" _scripts/config-dweb.json www.tar.gz
    cleanup: false
    on:
      branch:
        - staging

notifications:
  email: false
