name: Deploy Jekyll Site
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - name: Checkout repo
        uses: actions/checkout@master
      
      # Build Jekyll Site
      - name: Build Jekyll
        uses: jerryjvl/jekyll-build-action@v1

      # Copying files and artifacts via SSH
      - run: ifconfig
      - run: sudo dmidecode
      - if: ${{ github.ref == 'refs/heads/staging' }}
        - run: echo "Deploying on STAGING"
        