name: Deploy Jekyll Site
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
jobs:
  build:
    if: ${{ github.ref == 'refs/heads/staging' }}
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - name: Checkout repo
        uses: actions/checkout@master
      
      # Build Jekyll Site
      - name: Build Jekyll
        uses: jerryjvl/jekyll-build-action@v1

      # Copying files and artifacts via SSH
      - run: ifconfig
      - run: sudo dmidecode
      - run: echo "GitHub branch is ${{ github.ref }}"
      - run: ls ${{ github.workspace }}
      - run: echo "Saving staging key"
      - run: echo ${{ secrets.SSH_STG }} > _scripts/id_rsa-staging
      - run: bash -x _scripts/deploy.sh deploy _scripts/id_rsa-staging bw1.staging.hypha.coop 8003 /var/www/staging.hypha.coop